[General]
backgroundFillMode=aspect
background=#000000
type=theme
x11CursorTheme=Adwaita
x11CursorSize=24

[Interface]
passwordFontSize=24
passwordTextColor=#ffffff
passwordInputBackground=#1a1a1a
passwordInputRadius=8

[Users]
HideUsers=false
ShowAvatar=false
RememberLastUser=true
LayoutNames=
