[Autologin]
Relogin=false
Session=
User=

[General]
DisplayServer=x11
HaltCommand=/usr/bin/systemctl poweroff
InputMethod=qtvirtualkeyboard
Numlock=none
RebootCommand=/usr/bin/systemctl reboot
Theme=minimal
Current=minimal

[LightDM]

[Users]
DefaultPath=/usr/local/bin:/usr/bin:/bin
GreeterPath=/usr/bin/sddm-greeter
HideUsers=false
MaximumUid=60513
MinimumUid=1000
RememberLastSession=true
RememberLastUser=true
ShowAvatar=true
UserListFormat=username

[Wayland]
SessionDir=/usr/share/wayland-sessions

[X11]
ServerArguments=-nolisten local -dpi 144
Xserver=/usr/bin/X

[Security]
AllowRootLogin=true
